# Base configs
baseurl: "https://danielxchiu.github.io/chee-seong-photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Chee Seong Photography"
subtitle: "See the world through my eyes!"
author: "Chee Seong"
header:
  title: "Chee Seong Photography"